spring:
  application:
    name: opa-secure-microservice
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
opa:
  url: http://localhost:8181/v1/data/http/authz/allow

logging:
  level:
    de.az82: DEBUG
