apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opa-secure-microservice.fullname" . }}
  labels:
    {{- include "opa-secure-microservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opa-secure-microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opa-secure-microservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opa-secure-microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}    
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "opa-secure-microservice.fullname" . }}
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "opa-secure-microservice.fullname" . }}
                  key: GITHUB_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "opa-secure-microservice.fullname" . }}
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "opa-secure-microservice.fullname" . }}
                  key: GOOGLE_CLIENT_SECRET
        - name: opa
          securityContext:
            {{- toYaml .Values.opa.securityContext | nindent 12 }}
          image: "{{ .Values.opa.image.repository }}:{{ .Values.opa.image.tag }}"
          imagePullPolicy: {{ .Values.opa.image.pullPolicy }}
          args:
          - "run"
          - "--server"          
          resources:
            {{- toYaml .Values.opa.resources | nindent 12 }} 
        - name: kube-mgmt
          securityContext:
            {{- toYaml .Values.kubeMgmt.securityContext | nindent 12 }}
          image: openpolicyagent/kube-mgmt:0.11           
          imagePullPolicy: {{ .Values.kubeMgmt.image.pullPolicy }}
          resources:
            {{- toYaml .Values.kubeMgmt.resources | nindent 12 }} 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
