apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opa-secure-microservice.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}